/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  devops: [{ type: "autogenerated", dirName: "devops" }],
  backend: [{ type: "autogenerated", dirName: "backend" }],
  frontend: [{ type: "autogenerated", dirName: "frontend" }],
  memo: [{ type: "autogenerated", dirName: "memo" }],
  middleware: [{ type: "autogenerated", dirName: "middleware" }],
  solution: [{ type: "autogenerated", dirName: "solution" }],
  flight: [{ type: "autogenerated", dirName: "flight" }],
};
